### ISSUE TITLE
Default credentials file env variable

### ISSUE THREAD

**Issue by jum** [nanoandrew4/ngcplogs#1]
I am trying to use this plugin to log externally to gcp. With the builtin driver I could do this as a systemd drop-in for my docker daemon:

[Service]
Environment="GOOGLE_APPLICATION_CREDENTIALS=/home/jum/.serviceaccts/xxx.json"

But this does not appear to work with plugins. Do you have any pointer how to set this?

**Comment by nanoandrew4** [comment]
It would require me making some changes to the driver, so that it could read the JSON from your daemon.json, and use that for authentication. Would that work for your use case? I don' think I can make the driver read a file from outside the container it is run in, at least not that I am aware of.

**Comment by jum** [comment]
Actually, reviewing the options structure the logging.NewClient accepts, it would probably be the easiest if one would be able to specify some value in the json that would be saved by the driver in some accessible place, and set that copied file as an environment variable. 

The issue here in my case is that I do use gcplogs from outside the Google cloud infrastructure, for example in some Oracle and Hosteurope data centers. I have to specify the credentials to authenticate as a log writer.

**Comment by nanoandrew4** [comment]
Please try with the `latest` tag of the driver, and check the README for the new options to configure authentication. I have it working for me locally, if you can also validate it I will release a new version with the change.

**Comment by jum** [comment]
I have latest installed, and it works nicely, thank you! I will work with some more projects on it, and I have tested it with some logrus based project, and works nicely with github.com/andyfusniak/stackdriver-gae-logrus-plugin to format the json in a GCP compatible way. Now I have to find something similar for my newer slog based projects.

**Comment by nanoandrew4** [comment]
Version 1.2.0 is available with the changes described in the issue, so I will close it. Glad it worked!
