### ISSUE TITLE
Segfault in ngcplogs

### ISSUE THREAD

**Issue by jum** [nanoandrew4/ngcplogs#2]
If I start caddy in a container with ngpclogs activated, I get a segfault from ngcplogs, this is copied from my docker journal:

`
 time="2024-04-19T20:30:03+02:00" level=error msg="\t/go/src/github.com/nanoandrew4/ngcplogs/driver.go:100 +0x618" plugin=7ccf169cad92856feeb281a289fda828f41412330aef97c0ae094675cf9c0330
 time="2024-04-19T20:30:03+02:00" level=error msg="created by main.(*driver).StartLogging in goroutine 88" plugin=7ccf169cad92856feeb281a289fda828f41412330aef97c0ae094675cf9c0330
 time="2024-04-19T20:30:03+02:00" level=error msg="\t/go/src/github.com/nanoandrew4/ngcplogs/driver.go:121 +0x376" plugin=7ccf169cad92856feeb281a289fda828f41412330aef97c0ae094675cf9c0330
 time="2024-04-19T20:30:03+02:00" level=error msg="main.(*driver).consumeLog(0xc0003f0150, 0xc0004e0e00)" plugin=7ccf169cad92856feeb281a289fda828f41412330aef97c0ae094675cf9c0330
 time="2024-04-19T20:30:03+02:00" level=error msg="\t/go/src/github.com/nanoandrew4/ngcplogs/driver.go:142 +0x87" plugin=7ccf169cad92856feeb281a289fda828f41412330aef97c0ae094675cf9c0330
 time="2024-04-19T20:30:03+02:00" level=error msg="main.createMessageFromBuffer(0xc00027e200)" plugin=7ccf169cad92856feeb281a289fda828f41412330aef97c0ae094675cf9c0330
" plugin=7ccf169cad92856feeb281a289fda828f41412330aef97c0ae094675cf9c0330
 time="2024-04-19T20:30:03+02:00" level=error plugin=7ccf169cad92856feeb281a289fda828f41412330aef97c0ae094675cf9c0330
 time="2024-04-19T20:30:03+02:00" level=error msg="[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xad2167]" plugin=7ccf169cad92856feeb281a289fda828f41412330aef97c0ae094675cf9c0330
 time="2024-04-19T20:30:03+02:00" level=error msg="panic: runtime error: invalid memory address or nil pointer dereference" plugin=7ccf169cad92856feeb281a289fda828f41412330aef97c0ae094675cf9c0330
`

The log messages of caddy appear to be really long, could that be an issue?

**Comment by nanoandrew4** [comment]
That's interesting, I use it with caddy and have not observed the same behaviour. I'm away for 7 days, but I'll take a look when I get back. It probably has to do with something going wrong during the driver setup, as either the log pair or the glogger must be nil for that to happen.

-------- Original Message --------

**Comment by jum** [comment]
I tried it on my arm boxes, now works fine on 6 of them. But on my Debian amd64 machine I still get the segfault. It always dies after caddy docker-proxy logs the resulting newly build Caddyfile, so this is apparently too large.

**Comment by nanoandrew4** [comment]
Just pushed an updated amd64 image with the latest tag that may solve the issue, let me know if it does if possible

**Comment by jum** [comment]
I just tested this on the Intel box that would show this problem all the time, and the segfault is gone!

**Comment by nanoandrew4** [comment]
Awesome, I'll close the issue then. Thanks for the report.
